//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFirstMonoGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int Id { get; set; }
        public string Owner { get; set; }
        public int Health { get; set; }
        public int Strength { get; set; }
        public double Crit { get; set; }
        public int SpellPower { get; set; }
        public int Armor { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public int Place { get; set; }
        public int SellValue { get; set; }
        public int Quality { get; set; }
    }
}
