//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFirstMonoGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public string Id { get; set; }
        public int Health { get; set; }
        public int Strength { get; set; }
        public int Crit { get; set; }
        public int SpellPower { get; set; }
        public int Armor { get; set; }
        public int Level { get; set; }
        public int Xp { get; set; }
        public int Class { get; set; }
    }
}
